repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff linter
      entry: ruff
      language: system
      types: [python]
    - id: ruff-format
      name: ruff-format
      entry: ruff format
      language: system
      types: [python]
